export const CAMPAIGNS = [
    {
        id: 0,
        name: 'Powdered Beer - Just Add Carbonation',
        category: 'Food & Drink',
        image: 'assets/images/beer-3.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    },
    {
        id: 1,
        name: 'Hard-Shelled Suitcase With Charging Ports',
        category: 'Travel & Outdoors',
        image: 'assets/images/suitcase-1.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    },
    {
        id: 2,
        name: 'Offline Language Translation Earbuds',
        category: 'Technology',
        image: 'assets/images/earbuds-1.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    },
    {
        id: 3,
        name: 'Bring a Coworking Space to Sheboygan',
        category: 'Community Projects',
        image: 'assets/images/cowork-2.jpg', 
        featured: true, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    },
    {
        id: 4,
        name: 'Nail Stickers Made With Real Nail Polish',
        category: 'Skin, Hair, and Nails',
        image: 'assets/images/nails-orange.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    },
    {
        id: 5,
        name: 'Technology Conference - Northeast Wisconsin',
        category: 'Events & Conferences',
        image: 'assets/images/programming-1.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    }, 
    {
        id: 6,
        name: 'Belladonna Film Project',
        category: 'Film & Theater',
        image: 'assets/images/lights-camera.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    }, 
    {
        id: 7,
        name: 'Think Tank - Sheboygan, WI',
        category: 'Education & Innovation',
        image: 'assets/images/cowork-1.jpg', 
        featured: false, 
        description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    }
];